name: build and push docker image for Postgres

on:
  push:
    branches:
      - main

env:
  REG: ghcr.io
  NAME: ${{ github.repository }}  

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: login to GHCR
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REG }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create tags and labels for Docker
        id: labels
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7 
        with:
          images: ${{ env.REG }}/${{ env.NAME }}

      - name: build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.labels.outputs.tags }}
          labels: ${{ steps.labels.outputs.labels }}
