name: build and push docker image for Postgres

on:
  push:
    branches:
      - main

env:
  REG: ghcr.io
  

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: login to GHCR
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REG }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push Docker image
        run: |
          docker build . --tag ${{ env.REG }}/ryanamorrison/postgres-image:latest
          docker push ${{ env.REG }}/ryanamorrison/postgres-image:latest
