name: build and push docker image for Postgres

on:
  push:
    branches:
      - main

env:
  REG: ghcr.io
  NAME: ${{ github.repository }}  

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REG }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create tags and labels for Docker
        id: labels
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REG }}/${{ env.NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}


      - name: build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.labels.outputs.labels }}
